def problem_29():
    "How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?"

    # Create a set for the integer combinations
    integer_combinations = set()

    # For exponents and bases from 2 to 100, inclusive...
    for base in range(2, 100 + 1):
        for exponent in range(2, 100 + 1):
            # Calculate the base raised to the exponent
            power = base ** exponent
            # Add the power to the set of combinations
            integer_combinations.add(power)

    # Print the length of the combinations set
    length = len(integer_combinations)

    return length


if __name__ == "__main__":
    answer = problem_29()
    print(answer)
