name: Generate README

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.13"
      - name: Generate README.md
        run: python3 scripts/generate_readme.py
      - name: Set git user
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit and push README.md
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "Update README.md" && git push
          fi
