name: Test solutions

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test_solutions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.13"
      - name: Change working directory
        run: cd python
      - name: Run tests
        run: python3 python/tests.py
